In [1]:
import numpy as np
from qutip import Qobj, basis, tensor, identity, sigmax, sigmaz

# Define single-qubit identity and Pauli operators
I = identity(2)
X = sigmax()
Z = sigmaz()


In [2]:
# Construct the CNOT using the product-operator expansion
# CNOT_{(1->2)} = (1/2)*( I⊗I + Z⊗I + I⊗X - Z⊗X )
CNOT_12 = 0.5 * (tensor(I, I) 
                 + tensor(Z, I) 
                 + tensor(I, X) 
                 - tensor(Z, X))

# Print or inspect the resulting operator
print("CNOT gate (control qubit = 1, target qubit = 2):")
print(CNOT_12)


CNOT gate (control qubit = 1, target qubit = 2):
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]


In [3]:
ket0 = basis(2, 0)  # |0>
ket1 = basis(2, 1)  # |1>

states = {
    "|00>": tensor(ket0, ket0),
    "|01>": tensor(ket0, ket1),
    "|10>": tensor(ket1, ket0),
    "|11>": tensor(ket1, ket1),
}

print("Applying CNOT to computational basis states:")
for label, state in states.items():
    out_state = CNOT_12 * state
    print(f"CNOT |{label}> =")
    print(out_state)
    print()

superpos = (states["|00>"] + states["|10>"]).unit()
out_superpos = CNOT_12 * superpos
print("Superposition example:")
print("Initial state: (|00> + |10>) / sqrt(2)")
print("Result after CNOT:")
print(out_superpos)


Applying CNOT to computational basis states:
CNOT ||00>> =
Quantum object: dims=[[2, 2], [1, 1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]

CNOT ||01>> =
Quantum object: dims=[[2, 2], [1, 1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]]

CNOT ||10>> =
Quantum object: dims=[[2, 2], [1, 1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]]

CNOT ||11>> =
Quantum object: dims=[[2, 2], [1, 1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]]

Superposition example:
Initial state: (|00> + |10>) / sqrt(2)
Result after CNOT:
Quantum object: dims=[[2, 2], [1, 1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]]
